+ ncurses disk selection

diff --git a/install-os b/install-os
--- a/install-os
+++ b/install-os
@@ -11,6 +11,17 @@ prompt() {
 	fi
 }
 
+prompt_curse(){
+	dialog --yesno $1 0 0 2>&1 > /dev/tty || exit 1
+	return
+}
+
+sel_drive(){
+	DRIVE=$(dialog --menu "Choose the correct drive" 0 0 0 ${install_drive[@]} 2>&1 > /dev/tty)
+	[ -z $DRIVE ] && echo "[ ERROR ] Cancelled" && exit 1
+	prompt_curse "Are you sure $DRIVE is the correct location?"
+}
+
 checksudo() {
 	if [ "$(id -u)" != "0" ]; then
 		echo "[ ERROR ] Script must be run as sudo!" && exit 1
@@ -18,17 +29,19 @@ checksudo() {
 }
 
 diskpart() {
-	fdisk -l | grep "[A-Za-z]* /dev/[a-z]*" | sed 's/:.*//g ; s/^.* //g'
-	echo -e "\nChoose the disk: (/dev/sdX)"
-	read -r DRIVE
-	[ -z $DRIVE ] && echo "[ ERROR ] \$DRIVE can't be NULL" && exit 1
-	if [ $(fdisk -l | grep "$DRIVE" | wc -l) -gt 0 ]; then
-		echo "[ OK ] Found $DRIVE"
-	else 
-		echo "[ ERROR ] $DRIVE not found" && exit 1
-	fi
-	echo -e "\nAre you sure $DRIVE is the correct location? (yes/no)"
-	prompt
+	# fdisk -l | grep "[A-Za-z]* /dev/[a-z]*" | sed 's/:.*//g ; s/^.* //g'
+	# echo -e "\nChoose the disk: (/dev/sdX)"
+	# read -r DRIVE
+	# [ -z $DRIVE ] && echo "[ ERROR ] \$DRIVE can't be NULL" && exit 1
+	# if [ $(fdisk -l | grep "$DRIVE" | wc -l) -gt 0 ]; then
+	# 	echo "[ OK ] Found $DRIVE"
+	# else 
+	# 	echo "[ ERROR ] $DRIVE not found" && exit 1
+	# fi
+	# echo -e "\nAre you sure $DRIVE is the correct location? (yes/no)"
+	# prompt
+
+	sel_drive
 	echo ""
 	free --giga
 	echo -e "\nEnter your RAM value: (Eg: 5)"
