+ Fixed

diff --git a/install-os b/install-os
--- a/install-os
+++ b/install-os
@@ -10,7 +10,11 @@ checkdisks() {
 	fdisk -l
 	echo -e "\nChoose the disk: (/dev/sdX)"
 	read -r DRIVE
-	[ $(fdisk -l | grep "$DRIVE" | wc -l) -gt 0 ] && echo "[ OK ] Found $DRIVE" && exit 0 || echo "[ ERROR ] $DRIVE not found" && exit 1
+	if [ $(fdisk -l | grep "$DRIVE" | wc -l) -gt 0 ]; then
+		echo "[ OK ] Found $DRIVE"
+	else 
+		echo "[ ERROR ] $DRIVE not found" && exit 1
+	fi
 	echo ""
 	free --giga
 	echo -e "\nEnter your RAM value: (Eg: 5)"
