+ Typo protection

diff --git a/install-os b/install-os
--- a/install-os
+++ b/install-os
@@ -10,6 +10,7 @@ checkdisks() {
 	fdisk -l
 	echo -e "\nChoose the disk: (/dev/sdX)"
 	read -r DRIVE
+	[ $(fdisk -l | grep "$DRIVE" | wc -l) -gt 0 ] && echo "[ OK ] Found $DRIVE" || echo "[ ERROR ] $DRIVE not found" && exit 1
 	echo ""
 	free --giga
 	echo -e "\nEnter your RAM value: (Eg: 5)"
